[package]
name = "shared_structs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
glam = { workspace = true, features = ["bytemuck", "libm"] }
spirv-std.workspace = true
